---
# tasks file for git
    - name: Install Git package
      package:
        name: git
        state: present
      when: ansible_os_family == 'Debian'

    - name: Clone git repository for backend
      git:
        repo: "{{ backend }}"
        dest: "{{ file_path_backend }}"
      when: inventory_hostname == 'IP_ADDRESS_1'

    - name: Clone git repository for db
      git:
        repo: "{{ db }}"
        dest: "{{ file_path_db }}"
      when: inventory_hostname == 'IP_ADDRESS_2'
